# Generated by Django 5.0.4 on 2024-04-25 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen')),
                ('description', models.TextField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Categorias de productos',
                'db_table': 'producto_categoria',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Inventario',
                'db_table': 'inventario',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productocategoria', verbose_name='Categoria'),
        ),
    ]
