# Generated by Django 5.0.4 on 2024-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_product_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='description',
            field=models.TextField(default='', max_length=500, verbose_name='Descripcion'),
        ),
    ]
