# Generated by Django 5.0.4 on 2024-04-25 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_proveedor'),
        ('inventario', '0003_productocategoria_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', unique=True, verbose_name='Producto'),
        ),
    ]
