# Generated by Django 5.0.4 on 2024-04-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productocategoria_options_producto_proveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'db_table': 'compra_producto',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('pagado', 'Pagado')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Fecha de venta')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('products', models.ManyToManyField(through='inventario.CompraProducto', to='inventario.producto', verbose_name='Productos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Ordenes de compra',
                'db_table': 'orden_compra',
            },
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordencompra', verbose_name='Orden de compra'),
        ),
    ]
