# Generated by Django 5.0.4 on 2024-04-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_inventario_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraproducto',
            options={'verbose_name_plural': 'Compras de producto'},
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
    ]
