# Generated by Django 5.0.4 on 2024-04-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_compraproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compraproducto',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Compras de producto'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ordenes de compra'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de orden'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.FloatField(max_length=50, verbose_name='Precio'),
        ),
    ]
