# Generated by Django 5.0.4 on 2024-04-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_compraproducto_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoCategoria',
            new_name='Categoria',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
    ]
