# Generated by Django 5.0.4 on 2024-04-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_rename_productocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
