# Generated by Django 5.0.4 on 2024-05-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
