# Generated by Django 5.0.4 on 2024-05-10 03:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Fotos Publicitarias',
                'db_table': 'Foto Publicitaria',
            },
        ),
    ]
