# Generated by Django 5.0.4 on 2024-05-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name': 'Foto Publicitaria', 'verbose_name_plural': 'Fotos Publicitarias'},
        ),
    ]
