# Generated by Django 5.0.4 on 2024-05-21 00:20

import apps.marketing.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_banners_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosPromocionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, validators=[apps.marketing.models.file_validation], verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Promocional',
                'verbose_name_plural': 'Videos Promocionales',
                'db_table': 'Video Promocional',
            },
        ),
    ]
