# Generated by Django 5.0.4 on 2024-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_videospromocionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='videospromocionales',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
