# Generated by Django 5.0.4 on 2024-05-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_videospromocionales_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
